/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirpbo2;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhian
 */
public class Konfirmasi extends javax.swing.JFrame {

    koneksi con = new koneksi();
    String hutang;
    String harga;
    String bayar;
    int nambah;
    String idTrans;

    /**
     * Creates new form Konfirmasi
     */
    public Konfirmasi() {
        initComponents();
        setLocationRelativeTo(null);
        showData();
        status();
        jbSave.setEnabled(false);
        System.out.println(AmbilTanggal());
        System.out.println(akhirSewa());
    }

    public void showData() {
        String que = "select harga, bayar, hutang, akhirSewa, status, idTransaksi, nama_lengkap from sirum.data_rumah dr join sirum.pembelian p on dr.tipe_rumah=p.tipe_rumah join user u on p.idUser=u.idUser order by akhirSewa and hutang;";
        DefaultTableModel model = con.select(que);
        jtKonfirmasi.setModel(model);
    }

    public String status() {
        String[] status = {"Terkonfirmasi", "Belum"};
        for (int i = 0; i < status.length; i++) {
            jComboBox1.addItem(status[i]);
        }
        return (String) jComboBox1.getSelectedItem();
    }

    public String AmbilTanggal() {
        Date sekarang = new Date();
        SimpleDateFormat ddmmyy = new SimpleDateFormat("dd MMMM yyyy");
        return ddmmyy.format(sekarang);
    }

    public String akhirSewa() {
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, 1); // to get previous year add -1
        SimpleDateFormat fr = new SimpleDateFormat("dd MMMM yyyy");
        Date thDepan = cal.getTime();
        return fr.format(thDepan);
    }

    private void jtUserMousePressed(java.awt.event.MouseEvent evt) {
        int row = getRowTable();
        bayar = (String) getTableValue(row, 1);
        jtfBayar.setText(bayar);
        harga = (String) getTableValue(row, 0);
        idTrans = (String) getTableValue(row, 5);
    }

    public Object getTableValue(int a, int b) {
        Object value = jtKonfirmasi.getValueAt(a, b);
        return value;
    }

    public int getRowTable() {
        int row = jtKonfirmasi.getSelectedRow();
        return row;
    }

    public String hitungHarga() {
        String awal = bayar;
        String cicil = jtfBayar.getText();
        nambah = Integer.parseInt(awal) + Integer.parseInt(cicil);
        int hitung = Integer.parseInt(harga) - nambah;
        hutang = String.valueOf(hitung);
//        awal = String.valueOf(0);
        return hutang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpKonfir = new javax.swing.JPanel();
        jlJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtKonfirmasi = new javax.swing.JTable();
        jbEdit = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlBayar = new javax.swing.JLabel();
        jtfBayar = new javax.swing.JTextField();
        jlStatus = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpKonfir.setBackground(new java.awt.Color(0, 153, 153));

        jlJudul.setFont(new java.awt.Font("TypoUpright BT", 1, 48)); // NOI18N
        jlJudul.setForeground(new java.awt.Color(255, 255, 255));
        jlJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlJudul.setText("Konfirmasi");

        javax.swing.GroupLayout jpKonfirLayout = new javax.swing.GroupLayout(jpKonfir);
        jpKonfir.setLayout(jpKonfirLayout);
        jpKonfirLayout.setHorizontalGroup(
            jpKonfirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jpKonfirLayout.setVerticalGroup(
            jpKonfirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jpKonfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jtKonfirmasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtKonfirmasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 340));

        jbEdit.setBackground(new java.awt.Color(0, 153, 153));
        jbEdit.setForeground(new java.awt.Color(0, 0, 0));
        jbEdit.setText("Edit");
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, -1));

        jbSave.setBackground(new java.awt.Color(0, 153, 153));
        jbSave.setForeground(new java.awt.Color(0, 0, 0));
        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 80, -1));

        jbBack.setBackground(new java.awt.Color(0, 153, 153));
        jbBack.setForeground(new java.awt.Color(0, 0, 0));
        jbBack.setText("Back");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Konfirmasi Bayar"));

        jlBayar.setText("Bayar");

        jtfBayar.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jlStatus.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStatus)
                    .addComponent(jlBayar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfBayar)
                    .addComponent(jComboBox1, 0, 210, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBayar)
                    .addComponent(jtfBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlStatus)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 310, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        try {
            jtUserMousePressed(null);
            jbSave.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Klik data ditabel dulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        try {
            hitungHarga();
            System.out.println(hitungHarga());
            String update = "UPDATE `pembelian` SET `bayar`=" + nambah + ","
                    + "`status`='" + status() + "',"
                    + "`hutang`=" + hutang + ","
                    + "`tanggalSewa`='" + AmbilTanggal() + "',"
                    + "`akhirSewa`='" + akhirSewa() + "'"
                    + "WHERE idTransaksi=" + idTrans;
            con.insertUpdateDelete(update);
            showData();
            JOptionPane.showMessageDialog(rootPane, "Input Berhasil!");
            jtfBayar.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.dispose();
        new vAdmin().setVisible(true);
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konfirmasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlBayar;
    private javax.swing.JLabel jlJudul;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JPanel jpKonfir;
    private javax.swing.JTable jtKonfirmasi;
    private javax.swing.JTextField jtfBayar;
    // End of variables declaration//GEN-END:variables
}
