package tugasakhirpbo2;

import GalbertoTuwondila.Source.Image.ImagePreview;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.*;

/**
 *
 * @author DhIaN
 */
public class vAdmin extends javax.swing.JFrame {

    private koneksi con = new koneksi();
    File imageFile = null;
    boolean tbEdit = false;
    ImagePreview imagePreview = new ImagePreview();

    /**
     * Creates new form vAdmin
     */
    public vAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Admin Panel");
        jbSaveEdit.setVisible(false);
        jFileChooser1.setAccessory(imagePreview);
        jFileChooser1.addPropertyChangeListener(imagePreview);
    }

    public void showData() {
        String query = "SELECT * FROM data_rumah";
        DefaultTableModel model = con.select(query);
        jtRumah.setModel(model);
    }

    public void tombolEdit() {
        if (tbEdit == true) {
            jbEditRumah.setEnabled(false);
            jbDataUser.setEnabled(false);
            jbDeleteRumah.setEnabled(false);
            jbRefreshRumah.setEnabled(false);
            jbSave.setEnabled(false);
            jbSaveEdit.setVisible(true);
            tbEdit = false;
        } else if (tbEdit == false) {
            jbEditRumah.setEnabled(true);
            jbDataUser.setEnabled(true);
            jbDeleteRumah.setEnabled(true);
            jbRefreshRumah.setEnabled(true);
            jbSave.setEnabled(true);
            jbSaveEdit.setVisible(false);
        }
    }

    public void kosong() {
        jtfPilih.setText("");
        jtfNamaGB.setText("");
        jtfTipeRumah.setText("");
        jtfLuas.setText("");
        jTextArea1.setText("");
        jtfHarga.setText("");
        jtfStok.setText("");
    }

    private void jtRumahMousePressed(java.awt.event.MouseEvent evt) {
        int row = getRowTable();
        String pathGb = (String) getTableValue(row, 0);
        jtfPilih.setText(pathGb);
        String namaGb = (String) getTableValue(row, 1);
        jtfNamaGB.setText(namaGb);
        String tipeRumah = (String) getTableValue(row, 2);
        jtfTipeRumah.setText(tipeRumah);
        String luas = (String) getTableValue(row, 3);
        jtfLuas.setText(luas);
        String deskripsi = (String) getTableValue(row, 4);
        jTextArea1.setText(deskripsi);
        String harga = (String) getTableValue(row, 5);
        jtfHarga.setText(harga);
        String stok = (String) getTableValue(row, 6);
        jtfStok.setText(stok);
    }

    public Object getTableValue(int a, int b) {
        Object value = jtRumah.getValueAt(a, b);
        return value;
    }

    public int getRowTable() {
        int row = jtRumah.getSelectedRow();
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlNamaGB = new javax.swing.JLabel();
        jlPilih = new javax.swing.JLabel();
        jtfPilih = new javax.swing.JTextField();
        jtfNamaGB = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbBrowse = new javax.swing.JButton();
        jlNamaGB1 = new javax.swing.JLabel();
        jtfTipeRumah = new javax.swing.JTextField();
        jtfLuas = new javax.swing.JTextField();
        jlNamaGB2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlNamaGB3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRumah = new javax.swing.JTable();
        jbDeleteRumah = new javax.swing.JButton();
        jbEditRumah = new javax.swing.JButton();
        jbDataUser = new javax.swing.JButton();
        jbRefreshRumah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfStok = new javax.swing.JTextField();
        jbSaveEdit = new javax.swing.JButton();
        jbDataSewa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("TypoUpright BT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jlNamaGB.setText("Nama Gambar");

        jlPilih.setText("Pilih Gambar");

        jbSave.setBackground(new java.awt.Color(0, 153, 153));
        jbSave.setForeground(new java.awt.Color(0, 0, 0));
        jbSave.setText("Simpan");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbBrowse.setText("...");
        jbBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBrowseActionPerformed(evt);
            }
        });

        jlNamaGB1.setText("Tipe Rumah");

        jlNamaGB2.setText("Luas Rumah");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jlNamaGB3.setText("Deskripsi");

        jtRumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtRumah);

        jbDeleteRumah.setBackground(new java.awt.Color(0, 153, 153));
        jbDeleteRumah.setForeground(new java.awt.Color(0, 0, 0));
        jbDeleteRumah.setText("Delete");
        jbDeleteRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteRumahActionPerformed(evt);
            }
        });

        jbEditRumah.setBackground(new java.awt.Color(0, 153, 153));
        jbEditRumah.setForeground(new java.awt.Color(0, 0, 0));
        jbEditRumah.setText("Edit");
        jbEditRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditRumahActionPerformed(evt);
            }
        });

        jbDataUser.setBackground(new java.awt.Color(0, 153, 153));
        jbDataUser.setForeground(new java.awt.Color(0, 0, 0));
        jbDataUser.setText("Data User");
        jbDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataUserActionPerformed(evt);
            }
        });

        jbRefreshRumah.setBackground(new java.awt.Color(0, 153, 153));
        jbRefreshRumah.setForeground(new java.awt.Color(0, 0, 0));
        jbRefreshRumah.setText("Refresh");
        jbRefreshRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshRumahActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Media-Start-48.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("Harga");

        jLabel4.setText("Stok");

        jbSaveEdit.setBackground(new java.awt.Color(0, 153, 153));
        jbSaveEdit.setForeground(new java.awt.Color(0, 0, 0));
        jbSaveEdit.setText("Simpan");
        jbSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveEditActionPerformed(evt);
            }
        });

        jbDataSewa.setBackground(new java.awt.Color(0, 153, 153));
        jbDataSewa.setForeground(new java.awt.Color(0, 0, 0));
        jbDataSewa.setText("Data Sewa");
        jbDataSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataSewaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPilih)
                                .addGap(24, 24, 24)
                                .addComponent(jtfPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBrowse))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNamaGB)
                                    .addComponent(jlNamaGB1)
                                    .addComponent(jlNamaGB2)
                                    .addComponent(jlNamaGB3)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbDataSewa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbDataUser))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jtfTipeRumah)
                                    .addComponent(jtfNamaGB)
                                    .addComponent(jtfLuas)
                                    .addComponent(jtfHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfStok)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEditRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSaveEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDeleteRumah, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRefreshRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPilih)
                            .addComponent(jtfPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBrowse))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNamaGB)
                            .addComponent(jtfNamaGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNamaGB1)
                            .addComponent(jtfTipeRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNamaGB2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNamaGB3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbDataUser)
                            .addComponent(jbSave)
                            .addComponent(jbDataSewa))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbEditRumah)
                                .addComponent(jbDeleteRumah)
                                .addComponent(jbRefreshRumah))
                            .addGap(50, 50, 50))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(400, 400, 400)
                            .addComponent(jbSaveEdit))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBrowseActionPerformed
        // Hanya sastu file dalam satu file chooser
        jFileChooser1.setMultiSelectionEnabled(false);
        // Tipe dialog
        jFileChooser1.setDialogType(jFileChooser1.OPEN_DIALOG);
        // Ekstensi file yg dapat dipilih
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("JPEG, JPG, PNG", new String[]{"JPEG", "JPG", "PNG"}));
        // Judul FileChooser
        jFileChooser1.setDialogTitle("Pilih Gambar yang dikehendaki");

        // Tampilkan file chooser, jika aksi dari user adalah OPEN FILE
        if (jFileChooser1.showOpenDialog(imagePreview) == jFileChooser1.OPEN_DIALOG) {
            // Mengambil file yang dipilih oleh user dalam FileChooser
            imageFile = jFileChooser1.getSelectedFile();
            // Menampilan path file kedalam jTextName
            jtfPilih.setText(imageFile.getAbsolutePath());
            // Jika file terlalu besar
            if (imageFile.length() > Integer.MAX_VALUE) {
                JOptionPane.showMessageDialog(this, "File terlalu besar!");
            }
        }
    }//GEN-LAST:event_jbBrowseActionPerformed

    private void jbDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataUserActionPerformed
        this.dispose();
        new vDataUser().setVisible(true);
    }//GEN-LAST:event_jbDataUserActionPerformed

    private void jbRefreshRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshRumahActionPerformed
        showData();
    }//GEN-LAST:event_jbRefreshRumahActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        new vLogin().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        try {
            InputStream fis = new FileInputStream(imageFile);
            PreparedStatement statement = con.getKoneksi().prepareStatement("INSERT INTO `data_rumah`(`gambar`, "
                    + "`nama_gambar`, `tipe_rumah`, `luas_rumah/tanah`, "
                    + "`deskripsi`, `harga`, `stok`) VALUES "
                    + "(?,'"
                    + jtfNamaGB.getText() + "','"
                    + jtfTipeRumah.getText() + "','"
                    + jtfLuas.getText() + "','"
                    + jTextArea1.getText() + "','"
                    + jtfHarga.getText() + "','"
                    + jtfStok.getText() + "');");
            // mengisi data parameter pertama, yaitu gambar
            statement.setBlob(1, fis);
            // proses magic dimulai
            statement.executeUpdate();
            // tara!
            System.out.println("Insert success!");
//            imageFile = null;
            JOptionPane.showMessageDialog(this, "File anda sudah disimpan :)");
        } catch (Exception ex) {
            Logger.getLogger(JFileChooser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "File gagal disimpan :(\n" + ex.getMessage());
        }
        jtfPilih.setText("");
        jtfNamaGB.setText("");
        jtfTipeRumah.setText("");
        jtfLuas.setText("");
        jTextArea1.setText("");
        jtfHarga.setText("");
        jtfStok.setText("");
        System.out.println("Sukses");
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbEditRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditRumahActionPerformed
        jtRumahMousePressed(null);
        tbEdit = true;
        jtfStok.setEditable(false);
        tombolEdit();
    }//GEN-LAST:event_jbEditRumahActionPerformed

    private void jbDeleteRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteRumahActionPerformed
        int row = getRowTable();
        String tipeRumahDelete = (String) getTableValue(row, 2);
        System.out.println(tipeRumahDelete);
        try {
            String queDel = "DELETE FROM `sirum`.`data_rumah` "
                    + "WHERE `data_rumah`.`tipe_rumah` = " + tipeRumahDelete + "; ";
            con.insertUpdateDelete(queDel);
            JOptionPane.showMessageDialog(rootPane, "Delete Berhasil!", "Selamat", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Delete Gagal!", "Maaf", 2);
        }
        showData();
    }//GEN-LAST:event_jbDeleteRumahActionPerformed

    private void jbSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveEditActionPerformed
        try {
            int row = getRowTable();
            String tipeRumahUpdate = (String) getTableValue(row, 2);
            System.out.println(tipeRumahUpdate);
            InputStream fis = new FileInputStream(imageFile);
            PreparedStatement statement = con.getKoneksi().prepareStatement("UPDATE `data_rumah` SET `tipe_rumah`=" + tipeRumahUpdate + ","
                    + "`gambar`=?,"
                    + "`nama_gambar`='" + jtfNamaGB.getText() + "',"
                    + "`tipe_rumah`='" + jtfTipeRumah.getText() + "',"
                    + "`luas_rumah/tanah`='" + jtfLuas.getText() + "',"
                    + "`deskripsi`='" + jTextArea1.getText() + "',"
                    + "`harga`='" + jtfHarga.getText() + "',"
                    + "`stok`='" + jtfStok.getText() + "'"
                    + " WHERE `data_rumah`.`tipe_rumah` = " + tipeRumahUpdate + ";");
            statement.setBlob(1, fis);
            // proses magic dimulai
            statement.executeUpdate();
            // tara!
            System.out.println("Edit success!");
            showData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Edit Gagal!" + e + "", "Maaf", 2);
        }
        tbEdit = false;
        tombolEdit();
        kosong();
    }//GEN-LAST:event_jbSaveEditActionPerformed

    private void jbDataSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataSewaActionPerformed
        this.dispose();
        new Konfirmasi().setVisible(true);
    }//GEN-LAST:event_jbDataSewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbBrowse;
    private javax.swing.JButton jbDataSewa;
    private javax.swing.JButton jbDataUser;
    private javax.swing.JButton jbDeleteRumah;
    private javax.swing.JButton jbEditRumah;
    private javax.swing.JButton jbRefreshRumah;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSaveEdit;
    private javax.swing.JLabel jlNamaGB;
    private javax.swing.JLabel jlNamaGB1;
    private javax.swing.JLabel jlNamaGB2;
    private javax.swing.JLabel jlNamaGB3;
    private javax.swing.JLabel jlPilih;
    private javax.swing.JTable jtRumah;
    private javax.swing.JTextField jtfHarga;
    private javax.swing.JTextField jtfLuas;
    private javax.swing.JTextField jtfNamaGB;
    private javax.swing.JTextField jtfPilih;
    private javax.swing.JTextField jtfStok;
    private javax.swing.JTextField jtfTipeRumah;
    // End of variables declaration//GEN-END:variables
}
