package tugasakhirpbo2;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author dhian
 */
public class vLogin extends javax.swing.JFrame {

    private koneksi con = new koneksi();
    String saveId = null;

    /**
     * Creates new form vLogin
     */
    public vLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login SIRUM");
    }

    public String getUsername() {
        String namaPengguna = jtfUserName.getText();
        return namaPengguna;
    }

    public String getPassword() {
        String PassLogin = jpfPass.getText();
        return PassLogin;
    }

    public String[] getId(String userName) {
        String queId = "select * from user where username='" + userName + "'";
        return con.getData(queId, 1);
    }

    public String IDLogin() {
        String[] idLogin = getId(jtfUserName.getText());
        for (int i = 0; i < idLogin.length; i++) {
            saveId = idLogin[i];
        }
        return this.saveId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUserName = new javax.swing.JTextField();
        jpfPass = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        jlUserName = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        jlnotmember = new javax.swing.JLabel();
        jbReg = new javax.swing.JButton();
        jpBiru = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        jlSirum = new javax.swing.JLabel();
        jlLupaPass = new javax.swing.JLabel();
        jlGantiPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtfUserName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jpfPass.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jbLogin.setBackground(new java.awt.Color(0, 153, 153));
        jbLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbLogin.setText("Masuk");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jlUserName.setBackground(new java.awt.Color(0, 204, 204));
        jlUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-Profile-48.png"))); // NOI18N

        jlPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Login-01-48.png"))); // NOI18N

        jlnotmember.setText("Bukan Anggota? Silakan");

        jbReg.setBackground(new java.awt.Color(0, 153, 153));
        jbReg.setForeground(new java.awt.Color(0, 0, 0));
        jbReg.setText("Daftar");
        jbReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegActionPerformed(evt);
            }
        });

        jpBiru.setBackground(new java.awt.Color(0, 153, 153));

        jlLogin.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 48)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(102, 102, 102));
        jlLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogin.setText("Login");

        javax.swing.GroupLayout jpBiruLayout = new javax.swing.GroupLayout(jpBiru);
        jpBiru.setLayout(jpBiruLayout);
        jpBiruLayout.setHorizontalGroup(
            jpBiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBiruLayout.setVerticalGroup(
            jpBiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBiruLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlSirum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-48.png"))); // NOI18N
        jlSirum.setText("SIRUM");

        jlLupaPass.setText("Lupa Password?");

        jlGantiPass.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jlGantiPass.setText("Klik disini!");
        jlGantiPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGantiPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGantiPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBiru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlnotmember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jlPass))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlUserName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jpfPass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jlLupaPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlGantiPass)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSirum)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBiru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlSirum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUserName)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLupaPass)
                    .addComponent(jlGantiPass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnotmember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        String getAdmin = "dhian94";
        String query = "SELECT idUser, `username`, `password`  FROM `user` WHERE "
                + "`user`.`username`= '" + getUsername() + "' and "
                + "`user`.`password`= '" + getPassword() + "'";
        try {
            PreparedStatement pstmt = con.getKoneksi().prepareStatement(query);
            ResultSet rs = pstmt.executeQuery(query);
            if (getUsername().equals(getAdmin) && rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Selamat " + getUsername() + " Login Sukses!", "Selamat", 1);
                this.dispose();
                new vAdmin().setVisible(true);
            } else if (rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Selamat " + getUsername() + " Login Sukses!", "Selamat", 1);
                IDLogin();
                new vDeskRumah(saveId);
                System.out.println(saveId);

                this.dispose();
                new vHomeUser(saveId).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Login Gagal!", "Maaf", 2);
                jtfUserName.setText("");
                jpfPass.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegActionPerformed
        this.dispose();
        new vRegister().setVisible(true);
    }//GEN-LAST:event_jbRegActionPerformed

    private void jlGantiPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGantiPassMouseClicked
        this.dispose();
        new vGantiPassword().setVisible(true);
    }//GEN-LAST:event_jlGantiPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbReg;
    private javax.swing.JLabel jlGantiPass;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlLupaPass;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlSirum;
    private javax.swing.JLabel jlUserName;
    private javax.swing.JLabel jlnotmember;
    private javax.swing.JPanel jpBiru;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
