/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirpbo2;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DhIaN
 */
public class vSewa extends javax.swing.JFrame {

    koneksi con = new koneksi();
    String lgn;
    String tipe;
    String nmlgkp = null;
    String hasil;

    /**
     * Creates new form vHasil
     */
    public vSewa(String idUser, String tipeRumah, String nmlgkp, String tipe, String harga) {
        initComponents();
        setLocationRelativeTo(null);
        this.lgn = idUser;
        this.tipe = tipeRumah;
        System.out.println(lgn);
        System.out.println(tipe);
        jtfNamaBuyer.setEditable(false);
        jtfNamaBuyer.setText(nmlgkp);
        jtfTipe.setEditable(false);
        jtfTipe.setText(tipe);
        jtfHargaSewa.setEditable(false);
        jtfHargaSewa.setText(harga);
        AmbilTanggal();
        System.out.println(AmbilTanggal());
    }

    public String AmbilTanggal() {
        Date sekarang = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd MMMM yyyy");
        return df.format(sekarang);
    }

    public void insert() {
        String queIns = "INSERT INTO `pembelian`(`idUser`, `tipe_rumah`, "
                + "`bayar`, `status`, `hutang`, `tanggalSewa`, `akhirSewa`, "
                + "`noHP`, `noKTP`, idTransaksi) VALUES "
                + "(" + lgn + ","
                + "" + tipe + ","
                + "0,"
                + "'belum',"
                + "0,"
                + "'" + AmbilTanggal() + "',"
                + "NULL,"
                + "'" + jtfNoPe.getText() + "',"
                + "'" + jtfNoKTP.getText() + "',"
                + "NULL)";
        con.insertUpdateDelete(queIns);
    }

    public String[] ambilStok() {
        String queId = "select stok from data_rumah where tipe_rumah=" + tipe;
        return con.getData(queId, 1);
    }

    public String hitungStok() {
        String[] stokAwal = ambilStok();
        String temp = null;
        for (int i = 0; i < stokAwal.length; i++) {
            temp = stokAwal[i];
        }
        int hitung = Integer.parseInt(temp) - 1;
        hasil = String.valueOf(hitung);
        return this.hasil;
    }

    public void updateStok() {
        String queUpS = "UPDATE `data_rumah` SET `stok`=" + hasil + " WHERE tipe_rumah=" + tipe;
        con.insertUpdateDelete(queUpS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlJudul = new javax.swing.JLabel();
        jLNamaBuyer = new javax.swing.JLabel();
        jlAlamatBuyer = new javax.swing.JLabel();
        jlNoPe = new javax.swing.JLabel();
        jtfNamaBuyer = new javax.swing.JTextField();
        jtfTipe = new javax.swing.JTextField();
        jtfNoPe = new javax.swing.JTextField();
        jlNoKTP = new javax.swing.JLabel();
        jtfNoKTP = new javax.swing.JTextField();
        jbKonfirmasiUser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtfHargaSewa = new javax.swing.JTextField();
        jlNoPe1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jlJudul.setFont(new java.awt.Font("TypoUpright BT", 1, 48)); // NOI18N
        jlJudul.setForeground(new java.awt.Color(255, 255, 255));
        jlJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlJudul.setText("Sewa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLNamaBuyer.setText("Nama Lengkap");

        jlAlamatBuyer.setText("Tipe Rumah");

        jlNoPe.setText("No. Telepon/HP");

        jlNoKTP.setText("No KTP");

        jbKonfirmasiUser.setBackground(new java.awt.Color(0, 153, 153));
        jbKonfirmasiUser.setForeground(new java.awt.Color(0, 0, 0));
        jbKonfirmasiUser.setText("Konfirmasi Sewa");
        jbKonfirmasiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKonfirmasiUserActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlNoPe1.setText("Harga Sewa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbKonfirmasiUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNamaBuyer)
                            .addComponent(jlAlamatBuyer)
                            .addComponent(jlNoPe)
                            .addComponent(jlNoKTP)
                            .addComponent(jlNoPe1))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfHargaSewa)
                            .addComponent(jtfNamaBuyer, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jtfTipe)
                            .addComponent(jtfNoPe)
                            .addComponent(jtfNoKTP))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNamaBuyer)
                    .addComponent(jtfNamaBuyer, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlamatBuyer)
                    .addComponent(jtfTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNoPe1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNoPe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNoPe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNoKTP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKonfirmasiUser)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbKonfirmasiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKonfirmasiUserActionPerformed
        insert();
        JOptionPane.showMessageDialog(rootPane, "Sewa Sukses!\nSilakan Bayar dan Minta Konfirmasi!");
        updateStok();
        System.out.println(hitungStok());
        this.dispose();
        new vHomeUser(lgn).setVisible(true);
    }//GEN-LAST:event_jbKonfirmasiUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new vDeskRumah(lgn).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        </editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new vSewa(lgn, tipe).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLNamaBuyer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbKonfirmasiUser;
    private javax.swing.JLabel jlAlamatBuyer;
    private javax.swing.JLabel jlJudul;
    private javax.swing.JLabel jlNoKTP;
    private javax.swing.JLabel jlNoPe;
    private javax.swing.JLabel jlNoPe1;
    private javax.swing.JTextField jtfHargaSewa;
    private javax.swing.JTextField jtfNamaBuyer;
    private javax.swing.JTextField jtfNoKTP;
    private javax.swing.JTextField jtfNoPe;
    private javax.swing.JTextField jtfTipe;
    // End of variables declaration//GEN-END:variables
}
